{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.gist_flutter_module",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 5230066,
          "sha512": "6c177b03eea7bfed13c86bd06a94db39ba02e0ff7b3793d7086bad14b7503000b746505fa2b39ba79399a8c2e92b40d9de1c0f5cb601d29d1d1269042547e6d9",
          "sha256": "2fb24a5e6bfeecde204c121d4437659c45464fa98da4339044af48fbaeda017e",
          "sha1": "98a3978fbfae3954dc472040de54667012b1a7b6",
          "md5": "3c0297c826326f61bee4e3484d6a0b30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 5230066,
          "sha512": "6c177b03eea7bfed13c86bd06a94db39ba02e0ff7b3793d7086bad14b7503000b746505fa2b39ba79399a8c2e92b40d9de1c0f5cb601d29d1d1269042547e6d9",
          "sha256": "2fb24a5e6bfeecde204c121d4437659c45464fa98da4339044af48fbaeda017e",
          "sha1": "98a3978fbfae3954dc472040de54667012b1a7b6",
          "md5": "3c0297c826326f61bee4e3484d6a0b30"
        }
      ]
    }
  ]
}
